import "./globals.css";
import { Roboto, Noto_Sans_KR } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";

const notoSansKr = Noto_Sans_KR({
  // preload: true, 기본값
  subsets: ["latin"], // 또는 preload: false
  weight: ["400", "500", "700", "900"], // 가변 폰트가 아닌 경우, 사용할 fontWeight 배열
});

const roboto = Roboto({
  subsets: ["latin"], // preload에 사용할 subsets입니다.
  weight: ["500", "700", "900"],
  variable: "--roboto", // CSS 변수 방식으로 스타일을 지정할 경우에 사용합니다.
});

export const cls = (...classnames: string[]) => {
  return classnames.join(" ");
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={cls(notoSansKr.className, roboto.variable)}>
        <div className="w-[1060px] bg-[var(--bg-gray)] border-2 border-solid border-[var(--main-gray)] rounded-2xl mx-auto my-[91px]">
          <Header />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
